version: "3.8"

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - game-al

  app1:
    build: .
    container_name: app1
    networks:
      - game-al

  app2:
    build: .
    container_name: app2
    networks:
      - game-al

networks:
  game-al:
    driver: bridge

